### ISSUE TITLE
Catalog-of-things-ruby-Captsone Project ( For Code Reveiw )

### ISSUE THREAD

**Issue by Jawad-Nazari** [Jawad-Nazari/Catalog-of-things#6]
### Here is the link to the project repo
[Ruby_Capstone_Group_Project](https://github.com/Jawad-Nazari/Catalog-of-things/projects/1)

We are four members as below and agreed on the following assignation:
#Team member 1 :  @Elhambasir 
#Team member 2 :  @CaptainBawa 
#Team member 3 :  @Christelle-12 
#Team member 4:   @Jawad-Nazari

**Comment by ishimwezachee** [comment]
Great job to create the Kanban Board, you can go ahead and start your project 👍

**Comment by Elhambasir** [comment]
Thank you
